name: ci
on:
  push:
    branches:
      - master
      - main
permission:
  contents: write
jobs:
  deploy:
    runs-on: windows
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: action/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install mkdocs-materials
      - run: mkdocs gh-deploy --force